// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGWPFzgptOYilaug8tHpFhe3afuZmgFA',
    appId: '1:554490466079:web:57a0f6af9323f9d13d2a2a',
    messagingSenderId: '554490466079',
    projectId: 'mynotes-nuel',
    authDomain: 'mynotes-nuel.firebaseapp.com',
    storageBucket: 'mynotes-nuel.firebasestorage.app',
    measurementId: 'G-N52W4C66J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ThnsQE7twE7xg59THElJdY17u5E22wo',
    appId: '1:1005334961470:android:58959437ec2f8a3c97e06f',
    messagingSenderId: '1005334961470',
    projectId: 'mynote-nueltech-flutter',
    storageBucket: 'mynote-nueltech-flutter.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa_x8IIoeZPUkMXJX4L-5UGNe7yv4xf1s',
    appId: '1:1005334961470:ios:32a5aec7280651c397e06f',
    messagingSenderId: '1005334961470',
    projectId: 'mynote-nueltech-flutter',
    storageBucket: 'mynote-nueltech-flutter.firebasestorage.app',
    iosBundleId: 'dev.nueltech.mynotes',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaTVmKOU11HWAM_o1VJnMc9knKLW2iP6g',
    appId: '1:554490466079:ios:6ccbc21733ea60983d2a2a',
    messagingSenderId: '554490466079',
    projectId: 'mynotes-nuel',
    storageBucket: 'mynotes-nuel.firebasestorage.app',
    iosBundleId: 'dev.nueltech.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGWPFzgptOYilaug8tHpFhe3afuZmgFA',
    appId: '1:554490466079:web:ff8b83b15ec78f973d2a2a',
    messagingSenderId: '554490466079',
    projectId: 'mynotes-nuel',
    authDomain: 'mynotes-nuel.firebaseapp.com',
    storageBucket: 'mynotes-nuel.firebasestorage.app',
    measurementId: 'G-337WVFGTX2',
  );
}
